version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=safespace
    volumes:
      - mongodb_data:/data/db
    deploy:
      resources:
        reservations:
          memory: 512M

  # Frontend Service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
    volumes:
      - .:/app
      - /app/node_modules

  # Backend Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongodb
      - llm-service
    volumes:
      - ./backend:/app

  # LLM Microservice (Ollama)
  llm-service:
    build:
      context: ./llm-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./llm-service:/app
      - ollama_data:/root/.ollama
    deploy:
      resources:
        reservations:
          memory: 4G

volumes:
  mongodb_data:
  ollama_data: