version: '3.8'

services:
  # Frontend Service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
    volumes:
      - .:/app
      - /app/node_modules

  # Backend Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - LLM_SERVICE_URL=http://llm-service:8080
    depends_on:
      - llm-service
    volumes:
      - ./backend:/app

  # LLM Microservice (Ollama)
  llm-service:
    build:
      context: ./llm-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./llm-service:/app
      - ollama_data:/root/.ollama
    deploy:
      resources:
        reservations:
          memory: 4G

volumes:
  ollama_data: